baseURL = 'https://djenjny.github.io/'
languageCode = 'en-us'
title = 'Ethan Jones'
theme = 'hugo-coder'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  author = "Ethan Jones"
  info = "Cloud Engineer"
  avatarURL = "img/profile.jpg"
  description = "Cloud Engineer"

[[params.social]]
  name = "GitHub"
  icon = "fa fa-github"
  weight = 1
  url = "https://github.com/djenjny"

[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin"
  weight = 2
  url = "https://linkedin.com/in/mrjones318"

[[params.social]]
  name = "Email"
  icon = "fa-solid fa-envelope"
  weight = 3
  url = "https://mail.google.com/mail/?view=cm&to=ethan.jon32@gmail.com"

[[params.social]]
  name = "Phone"
  icon = "fa-solid fa-phone"
  weight = 4
  url = "tel:516-373-9905"


sectionPagesMenu = 'main'



